openapi: 3.1.0
info:
  title: Garden Planning API
  description: API for retrieving weather, soil, and plant data for garden planning
  version: 1.0.0

servers:
  - url: /api/v1
    description: Base API path

paths:
  /weather/frost-dates:
    get:
      summary: Get frost dates for a specific location
      parameters:
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Latitude of the location
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Longitude of the location
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FrostDates'
        '400':
          $ref: '#/components/responses/BadRequest'

  /weather/frost-dates:
    post:
      summary: Get frost dates for a GeoJSON area
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                geojson_file:
                  type: string
                  description: Path to GeoJSON file
              required:
                - geojson_file
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FrostDates'
        '400':
          $ref: '#/components/responses/BadRequest'

  /weather/hardiness-zone:
    get:
      summary: Get USDA hardiness zone for a location
      parameters:
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Latitude of the location
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Longitude of the location
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  hardiness_zone:
                    type: string
                    example: "7a"
        '400':
          $ref: '#/components/responses/BadRequest'

  /soil/type:
    get:
      summary: Get soil type information for a location
      parameters:
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Latitude of the location
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Longitude of the location
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SoilType'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          description: No soil data found for location

  /plants/native:
    get:
      summary: Get native plants observed in an area
      parameters:
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Latitude of the location
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Longitude of the location
        - name: radius
          in: query
          required: false
          schema:
            type: integer
            default: 50
          description: Search radius in kilometers
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NativePlants'
        '400':
          $ref: '#/components/responses/BadRequest'

  /weather/monthly-averages:
    get:
      summary: Get monthly weather averages for a location
      parameters:
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Latitude of the location
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Longitude of the location
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MonthlyAverages'
        '400':
          $ref: '#/components/responses/BadRequest'

components:
  schemas:
    FrostDates:
      type: object
      properties:
        frost_dates_by_year:
          type: object
          additionalProperties:
            type: object
            properties:
              last_spring_frost:
                type: string
                format: date
                nullable: true
              first_fall_frost:
                type: string
                format: date
                nullable: true
        average_last_frost:
          type: string
          format: date
          nullable: true
        average_first_frost:
          type: string
          format: date
          nullable: true
        earliest_last_frost:
          type: string
          format: date
          nullable: true
        latest_last_frost:
          type: string
          format: date
          nullable: true
        earliest_first_frost:
          type: string
          format: date
          nullable: true
        latest_first_frost:
          type: string
          format: date
          nullable: true

    SoilType:
      type: object
      properties:
        map_unit_symbol:
          type: string
          example: "2nC"
        map_unit_name:
          type: string
          example: "Portneuf silt loam, 2 to 4 percent slopes"
        map_unit_key:
          type: string
          example: "123456"

    NativePlants:
      type: object
      properties:
        plants:
          type: array
          items:
            type: string
          example: ["Artemisia tridentata", "Pinus ponderosa"]
        count:
          type: integer
          example: 42
        radius_km:
          type: integer
          example: 50

    MonthlyAverages:
      type: object
      properties:
        monthly_averages:
          type: object
          additionalProperties:
            type: object
            properties:
              average_temp_c:
                type: number
                format: float
                example: 15.2
                description: Average temperature in Celsius
              average_precipitation_mm:
                type: number
                format: float
                example: 45.7
                description: Average precipitation in millimeters
              average_sunshine_mins:
                type: number
                format: float
                example: 18240
                description: Average sunshine duration in minutes

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string 